name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railwayapp/cli-action@v1.5.0
        with:
          service: ${{ secrets.RAILWAY_SERVICE_ID }}
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
